CREATE TABLE CUSTOMER (CUSTOMER_ID BIGINT, CUSTOMER_NAME VARCHAR2(50),
PRIMARY KEY (CUSTOMER_ID) );

CREATE TABLE TRANSACTION (TRANSACTION_ID BIGINT, TRANSACTION_DATE DATE, TRANSACTION_AMOUNT Decimal(10,0),CUSTOMER_ID BIGINT,
PRIMARY KEY (TRANSACTION_ID),
FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER(CUSTOMER_ID));